### ISSUE TITLE
Compatibility with symfony 5.x and PHP 8

### ISSUE THREAD

**Issue by W0rma** [propelorm/PropelBundle#505]
I noticed that https://github.com/propelorm/Propel2 was revived. It would be great to see this symfony bundle being revived, too.

https://github.com/propelorm/PropelBundle/pull/504 has already started to add compatibility with symfony 5.x. However, it drops support for PHP <7.4.

Before working on a pull request I'd like to ask some questions:

1. Is the branching model described in https://github.com/propelorm/PropelBundle#branching-model still valid or should we just try to make 4.0 compatible with symfony 5.x and PHP 8?
2. Can we drop support for PHP <7.3?
3. Can we drop support for PHP 7.3?
4. Probably the most important question: who does currently maintain this bundle?

**Comment by W0rma** [comment]
@dereuromark I noticed that you did a lot of work on https://github.com/propelorm/Propel2 during the last months. Do you know if this symfony bundle is still maintained and who is in charge of merging pull requests?

**Comment by dereuromark** [comment]
I dont have any commit rights.
@propelorm/propel2 might be able to help.

**Comment by SkyFoxvn** [comment]
symfony propel bundle it's hardly to tell its been revived because the owner of the repo dosant look like its have any interest of it.
But its true that i made it work with symfony 5 and i didnt spend enough time to make it properly mainly because i simple made it for me use.

Now i did have some time and i made few changes:
1. bundle support 7.2+
2. added 4+ no bundle structure(mainly used in form generation for which maker bundle also can be userd)
3. fix the test to run for PHP 7.2 - 8 and symfony 4.4 - 5.2
4. update readme.md

about the W0rma questions i think i can answer to only question 4 look like i do maintain it :) i wasant able to find any other fork which of the bundle which make some changes on it. 
About how long i will work on this i cant give you answer right now i start it at first place because i have a single project which i wanted to update but as most of the ppl which use symfony i also did start to use doctrine regardless of that i like propel because of the lack of maintenance

**Comment by dereuromark** [comment]
I would suggest making a forked package and start to maintain that.
Here it seems not much will happen any time soon.

**Comment by SkyFoxvn** [comment]
yeah it seems nothing will happen :) im thinking about that to publish it in https://packagist.org/ but i have not decided yet it will take some commitment if i do it :) so we will see next few days :)

**Comment by SkyFoxvn** [comment]
I decide to make it as package and maintain it for now at least enough to work with current versions of Symfony and new one but im open for any suggestions for improvement.

https://packagist.org/packages/skyfox/propel-bundle

**Comment by dereuromark** [comment]
We deprecated now this and linked it to yours: https://github.com/SkyFoxvn/PropelBundle
